services:
  - type: web
    name: nba-dashboard
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python etl/pipeline.py
    startCommand: gunicorn dashboard.app_modern:server --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
